Lineage pull request for: skeleton
cisagov/skeleton-aws-lambda pull request #29
Opened 2021-08-26 18:39 UTC by cisagovbot

# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2021-08-26 19:47 UTC, jsf9k approved these changes

2021-08-26 20:25 UTC, dav3r approved these changes

2021-08-27 18:08 UTC, jsf9k requested changes

2021-08-27 18:08 UTC, jsf9k commented on .github/workflows/build.yml
> +          - 3.8
Python 3.9 is now supported in AWS Lambda.
```suggestion
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
```

2021-08-27 18:08 UTC, jsf9k commented on .github/workflows/release.yml
> +          - 3.8
```suggestion
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
```

2021-08-27 18:16 UTC, mcdonnnj commented on .github/workflows/build.yml
> +          - 3.8
However there is no image for [lambci/lambda](https://hub.docker.com/r/lambci/lambda/tags?page=1&ordering=last_updated&name=build-python3.9). I would like to keep changes like that to their own PRs as well.

2021-08-27 18:24 UTC, jsf9k commented on .github/workflows/build.yml
> +          - 3.8
Ah, OK.

2021-08-27 18:24 UTC, jsf9k commented on .github/workflows/release.yml
> +          - 3.8
@mcdonnnj pointed out that there is no Python 3.9 Docker `lambci/lambda` image available yet.

2021-08-27 18:25 UTC, jsf9k approved these changes

2021-08-27 18:29 UTC, dav3r approved these changes
👍

2021-08-27 18:35 UTC, merged